#!/bin/bash
# Prepares Kaui and the Kill Bill tenant once Kill Bill is running. Runs in the
# Kaui image on every `docker compose up` and is safe to repeat:
# - Kaui's database schema (on an empty `kaui` database) and its allowed
#   admin user.
# - Kaui's encryption key (a file in the `kaui_config` volume, generated once):
#   the image's own key is public.
# - The tenant (KILLBILL_API_KEY / KILLBILL_API_SECRET), created through the
#   Kill Bill API if missing.
# - The tenant's push notification callback (KILLBILL_NOTIFICATION_URL).
# - The tenant's invoice texts for KILLBILL_INVOICE_LOCALE (Spanish, from
#   config/killbill/InvoiceTranslation.properties and the company variables).
# - The email plugin's tenant configuration (SMTP_*, KILLBILL_EMAIL_EVENTS;
#   no emails without SMTP_HOST) and its Spanish texts
#   (config/killbill/EmailTranslation.properties).
# - The tenant registered in Kaui for the admin user, so Kaui opens it after
#   login (otherwise Kaui asks for the API key and secret).
# Runs as root only to write the key file for Kaui's user (tomcat).
set -euo pipefail

WEB_INF=/var/lib/tomcat/webapps/ROOT/WEB-INF
ENCRYPTION_FILE="${KAUI_ENCRYPTION_FILENAME}"
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

cat > "${WORK}/db.cnf" <<CNF
[client]
host=${DB_HOST}
port=${DB_PORT}
user=${DB_USER}
password=${DB_PASSWORD}
CNF
sql() { mysql --defaults-extra-file="${WORK}/db.cnf" --batch --skip-column-names kaui "$@"; }
sql_quote() { printf "'%s'" "${1//\'/\'\'}"; }

# Kill Bill API as the admin user (credentials in a curl config file, escaped
# for its quoted syntax); the tenant headers only where needed.
cred="${KILLBILL_ADMIN_USER}:${KILLBILL_ADMIN_PASSWORD}"
cred="${cred//\\/\\\\}"
printf 'user = "%s"\n' "${cred//\"/\\\"}" > "${WORK}/curl.cnf"
kb() {
    curl -sS --config "${WORK}/curl.cnf" -H 'X-Killbill-CreatedBy: setup' "$@"
}
kb_tenant() {
    kb -H "X-Killbill-ApiKey: ${KILLBILL_API_KEY}" -H "X-Killbill-ApiSecret: ${KILLBILL_API_SECRET}" "$@"
}
json() { python3 -c "import json, sys; print(json.load(sys.stdin)$1)"; }
# First value of a tenant key-value JSON answer ({"values": [...]}), "" if none.
first_value() { python3 -c 'import json, sys
try:
    values = json.load(sys.stdin).get("values") or []
except ValueError:
    values = []
sys.stdout.write(values[0] if len(values) == 1 else "")'; }
# Replaces a tenant value (upload endpoint $1, file $2) only if it changed.
# POST adds a value to the existing ones: delete first (plugins ignore keys
# with several values). Prints "updated" when it changed.
tenant_value() {
    local url="${KILLBILL_INTERNAL_URL}/1.0/kb/tenants/$1"
    if [ "$(kb_tenant "${url}" | first_value)" != "$(cat "$2")" ]; then
        kb_tenant -f -o /dev/null -X DELETE "${url}" || true
        kb_tenant -f -o /dev/null -X POST -H 'Content-Type: text/plain' --data-binary "@$2" "${url}"
        echo "    updated"
    fi
}

echo "==> Kaui database"
if [ "$(sql -e 'SHOW TABLES' | wc -l)" = 0 ]; then
    sql < "$(find "${WEB_INF}/gems/gems" -path '*/kaui-*/db/ddl.sql' | head -1)"
fi
sql -e "INSERT IGNORE INTO kaui_allowed_users (kb_username, description, created_at, updated_at)
        VALUES ($(sql_quote "${KILLBILL_ADMIN_USER}"), 'Kill Bill admin', NOW(), NOW())"

if [ ! -s "${ENCRYPTION_FILE}" ]; then
    echo "==> Kaui encryption key"
    umask 077
    cat > "${ENCRYPTION_FILE}" <<YAML
# Generated by setup.sh: encrypts the tenant API secrets stored in Kaui's
# database. Back it up with the database (without it, register the tenant
# in Kaui again).
production:
  ciphers:
    - key: $(openssl rand -hex 16)
      iv: $(openssl rand -hex 8)
      cipher_name: aes-256-cbc
      encoding: :base64strict
      version: 1
YAML
    chown tomcat:tomcat "${ENCRYPTION_FILE}"
fi

echo "==> Tenant ${KILLBILL_TENANT_NAME}"
# Kill Bill answers 500 (not 404) for an unknown API key: create the tenant
# and accept "already exists" (409) instead of looking it up first.
body="$(python3 -c 'import json, os; print(json.dumps({"apiKey": os.environ["KILLBILL_API_KEY"], "apiSecret": os.environ["KILLBILL_API_SECRET"], "externalKey": os.environ["KILLBILL_TENANT_NAME"]}))')"
status="$(kb -o "${WORK}/create.json" -w '%{http_code}' -X POST -H 'Content-Type: application/json' \
    -d "${body}" "${KILLBILL_INTERNAL_URL}/1.0/kb/tenants")"
case "${status}" in
    201) echo "    created" ;;
    409) ;;
    *) echo "Kill Bill answered ${status} creating the tenant:" >&2; cat "${WORK}/create.json" >&2; exit 1 ;;
esac
kb -f -o "${WORK}/tenant.json" "${KILLBILL_INTERNAL_URL}/1.0/kb/tenants?apiKey=${KILLBILL_API_KEY}"
tenant_id="$(json '["tenantId"]' < "${WORK}/tenant.json")"
# The API secret can't be changed afterwards: check it still matches.
status="$(kb_tenant -o /dev/null -w '%{http_code}' "${KILLBILL_INTERNAL_URL}/1.0/kb/tenants/userKeyValue/docker-stack")"
if [ "${status}" = 401 ]; then
    echo "KILLBILL_API_SECRET doesn't match the secret of tenant ${KILLBILL_API_KEY} (it can't be changed)." >&2
    exit 1
fi

echo "==> Notification callback"
kb_tenant -f -o "${WORK}/callbacks.json" \
    "${KILLBILL_INTERNAL_URL}/1.0/kb/tenants/registerNotificationCallback" || echo '{"values": []}' > "${WORK}/callbacks.json"
current="$(python3 -c 'import json, sys; print(",".join(json.load(sys.stdin).get("values") or []))' < "${WORK}/callbacks.json")"
if [ "${current}" != "${KILLBILL_NOTIFICATION_URL:-}" ]; then
    if [ -n "${current}" ]; then
        kb_tenant -f -o /dev/null -X DELETE "${KILLBILL_INTERNAL_URL}/1.0/kb/tenants/registerNotificationCallback"
    fi
    if [ -n "${KILLBILL_NOTIFICATION_URL:-}" ]; then
        kb_tenant -f -o /dev/null -X POST -G --data-urlencode "cb=${KILLBILL_NOTIFICATION_URL}" \
            "${KILLBILL_INTERNAL_URL}/1.0/kb/tenants/registerNotificationCallback"
    fi
    echo "    updated: ${KILLBILL_NOTIFICATION_URL:-(none)}"
fi

echo "==> Invoice translation (${KILLBILL_INVOICE_LOCALE})"
envsubst < /usr/local/share/stack/config/InvoiceTranslation.properties > "${WORK}/translation.properties"
url="${KILLBILL_INTERNAL_URL}/1.0/kb/invoices/translation/${KILLBILL_INVOICE_LOCALE}"
status="$(kb_tenant -H 'Accept: text/plain' -o "${WORK}/current.properties" -w '%{http_code}' "${url}")"
if [ "${status}" != 200 ] || ! cmp -s "${WORK}/current.properties" "${WORK}/translation.properties"; then
    kb_tenant -f -o /dev/null -X POST -H 'Content-Type: text/plain' \
        --data-binary "@${WORK}/translation.properties" "${url}?deleteIfExists=true"
    echo "    updated"
fi

echo "==> Email notifications (plugin killbill-email-notifications)"
# The plugin's SMTP client: useSSL = SMTPS (implicit TLS, port 465) and
# STARTTLS together; without it, plain SMTP (no STARTTLS).
smtp_secure="$(echo "${SMTP_SECURE:-}" | tr '[:upper:]' '[:lower:]')"
if [ "${smtp_secure}" = tls ]; then
    echo "WARNING: SMTP_SECURE=tls (STARTTLS) is not supported by the email plugin:" \
        "use SMTP_SECURE=ssl (SMTPS, usually port 465)." >&2
fi
events=""
[ -n "${SMTP_HOST:-}" ] && events="${KILLBILL_EMAIL_EVENTS}"
prefix=org.killbill.billing.plugin.email-notifications
cat > "${WORK}/email.properties" <<PROPERTIES
${prefix}.defaultEvents=${events}
${prefix}.smtp.host=${SMTP_HOST:-}
${prefix}.smtp.port=${SMTP_PORT:-25}
${prefix}.smtp.useAuthentication=$([ -n "${SMTP_USER:-}" ] && echo true || echo false)
${prefix}.smtp.userName=${SMTP_USER:-}
${prefix}.smtp.password=${SMTP_PASSWORD:-}
${prefix}.smtp.useSSL=$([ "${smtp_secure}" = ssl ] && echo true || echo false)
${prefix}.smtp.defaultSender=${SMTP_FROM:-}
${prefix}.smtp.sendHTMLEmail=true
${prefix}.credentials.username=${KILLBILL_ADMIN_USER}
${prefix}.credentials.password=${KILLBILL_ADMIN_PASSWORD}
PROPERTIES
tenant_value uploadPluginConfig/killbill-email-notifications "${WORK}/email.properties"
envsubst < /usr/local/share/stack/config/EmailTranslation.properties > "${WORK}/email-translation.properties"
tenant_value "userKeyValue/killbill-email-notifications:TEMPLATE_TRANSLATION_${KILLBILL_INVOICE_LOCALE}" \
    "${WORK}/email-translation.properties"

echo "==> Tenant in Kaui"
if [ -z "$(sql -e "SELECT id FROM kaui_tenants WHERE kb_tenant_id = $(sql_quote "${tenant_id}")")" ]; then
    # Encrypted the way Kaui does it (symmetric-encryption gem, no random IV).
    encrypted="$(cd "${WEB_INF}" && GEM_HOME="${WEB_INF}/gems" GEM_PATH="${WEB_INF}/gems" \
        java -cp "$(ls lib/jruby-core-*-complete.jar):$(ls lib/jruby-stdlib-*.jar)" org.jruby.Main -e '
            require "symmetric-encryption"
            SymmetricEncryption.load!(ENV["KAUI_ENCRYPTION_FILENAME"], "production")
            print SymmetricEncryption.encrypt(ENV["KILLBILL_API_SECRET"], random_iv: false)')"
    sql <<SQL
INSERT INTO kaui_tenants (name, kb_tenant_id, api_key, encrypted_api_secret, created_at, updated_at)
VALUES ($(sql_quote "${KILLBILL_TENANT_NAME}"), $(sql_quote "${tenant_id}"), $(sql_quote "${KILLBILL_API_KEY}"),
        $(sql_quote "${encrypted}"), NOW(), NOW());
INSERT IGNORE INTO kaui_allowed_user_tenants (kaui_allowed_user_id, kaui_tenant_id, created_at, updated_at)
SELECT u.id, t.id, NOW(), NOW() FROM kaui_allowed_users u, kaui_tenants t
WHERE u.kb_username = $(sql_quote "${KILLBILL_ADMIN_USER}") AND t.kb_tenant_id = $(sql_quote "${tenant_id}");
SQL
    echo "    registered"
fi

echo "==> Done: tenant ${KILLBILL_TENANT_NAME} (${tenant_id})"
echo "    Kaui: ${KILLBILL_URL} (user ${KILLBILL_ADMIN_USER})"
echo "    API:  ${KILLBILL_URL}/1.0/kb (API key ${KILLBILL_API_KEY})"
